services:
  web:
    extends:
      file: docker-compose.yml
      service: app
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
    working_dir: /app
    command: make dev    

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443 
    volumes:
       - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
       - caddy_data:/data
       - caddy_config:/config    
    depends_on:
      - web

volumes:
  caddy_data:
  caddy_config:        
