services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: zhedevops/devops-project-74  

  tests:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test   
    image: zhedevops/devops-for-programmers-project-74
    depends_on: [db] 

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}          
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3    
