services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: zhedevops/devops-project-74

  tests:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test    
