services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: zhedevops/devops-project-74
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}     

  tests:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test   
    image: zhedevops/devops-for-programmers-project-74
    environment:
      DATABASE_HOST: db 
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD:  password 
    depends_on: 
      db: 
        condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 1s
      timeout: 3s
      retries: 3     
