name: CI on push

on:
  push:
    branches: [ "main" ]

env:
  APP_IMAGE_NAME: zhedevops/devops-for-programmers-project-74
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # checkout — клонирует репозиторий
    - uses: actions/checkout@v3

    - name: copy env
      run: cp -n .env.example .env

    - name: run tests
      run: make compose-ci  
      
    - name: del env
      run: rm .env 
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile.production --tag latest:$(date +%s)

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}  

    - name: Build App
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile.production
        cache-from: type=registry,ref=${{ env.APP_IMAGE_NAME }}
        cache-to: type=inline
        push: true
        tags: ${{ env.APP_IMAGE_NAME }}
